### ISSUE TITLE
obj defaults to Cobblestone in Actions.Give

### ISSUE THREAD

**Issue by jmnoss** [jhaip/minecraft-put-that-there#39]
"give" or "throw" with no object specified causes Jack to give Cobblestone

**Comment by jhaip** [comment]
The problem was when obj = False, the statement

```
obj in objToBlockTypes
```

would return true because objToBlockTypes[False] = objToBlockTypes[0] = objToBlockTypes[Objects.House].  

The real issue here was treating Objects.House as an enum value when it was really just set to equal 0.  This was fixed by making class Objects and Actions real python enum classes with the **enum** module.

Fixed in https://github.com/jhaip/minecraft-put-that-there/commit/5b40f7fcbabea0f548a74cfd4ba9e96ad7a92f78
